# Generated by Django 2.2.7 on 2019-12-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_auto_20191204_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
